export const products = [
  {
    id: 1,
    name: "Tai nghe không dây cao cấp",
    category: "Điện tử",
    price: 299.99,
    originalPrice: 399.99,
    rating: 4.8,
    reviews: 1243,
    image: "https://images.unsplash.com/photo-1761005653657-0885604ddbcd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcmVtaXVtJTIwaGVhZHBob25lcyUyMGVsZWN0cm9uaWNzfGVufDF8fHx8MTc2Mjc2MTQ4NXww&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1761005653657-0885604ddbcd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcmVtaXVtJTIwaGVhZHBob25lcyUyMGVsZWN0cm9uaWNzfGVufDF8fHx8MTc2Mjc2MTQ4NXww&ixlib=rb-4.1.0&q=80&w=1080",
      "https://images.unsplash.com/photo-1761005653657-0885604ddbcd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcmVtaXVtJTIwaGVhZHBob25lcyUyMGVsZWN0cm9uaWNzfGVufDF8fHx8MTc2Mjc2MTQ4NXww&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 24,
    brand: "AudioPro",
    description: "Trải nghiệm chất lượng âm thanh cao cấp với chống ồn chủ động và pin 40 giờ. Hoàn hảo cho người yêu nhạc và chuyên gia.",
    specifications: {
      "Thời lượng pin": "40 giờ",
      "Kết nối": "Bluetooth 5.2",
      "Trọng lượng": "250g",
      "Kích thước driver": "40mm"
    },
    colors: ["Đen", "Bạc", "Xanh navy"],
    sizes: [],
    featured: true,
    trending: true,
    discount: 25,
  },
  {
    id: 2,
    name: "Đồng hồ thông minh Pro",
    category: "Điện tử",
    price: 449.99,
    originalPrice: 549.99,
    rating: 4.6,
    reviews: 892,
    image: "https://images.unsplash.com/photo-1758348844371-dfbae2780bd3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBzbWFydHdhdGNoJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NjI3MDQ2MzB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1758348844371-dfbae2780bd3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBzbWFydHdhdGNoJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NjI3MDQ2MzB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 15,
    brand: "TechWatch",
    description: "Luôn kết nối với tính năng theo dõi sức khỏe nâng cao, GPS và mặt đồng hồ tùy chỉnh. Chống nước đến 50m.",
    specifications: {
      "Màn hình": "1.9 AMOLED",
      "Pin": "3 ngày",
      "Kháng nước": "50m",
      "Cảm biến": "Nhịp tim, SpO2, GPS"
    },
    colors: ["Đen", "Vàng hồng", "Titan"],
    sizes: ["42mm", "46mm"],
    featured: true,
    trending: false,
    discount: 18,
  },
  {
    id: 3,
    name: "Tai nghe nhét tai không dây Elite",
    category: "Điện tử",
    price: 179.99,
    originalPrice: 229.99,
    rating: 4.7,
    reviews: 2156,
    image: "https://images.unsplash.com/photo-1627989580309-bfaf3e58af6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aXJlbGVzcyUyMGVhcmJ1ZHN8ZW58MXx8fHwxNzYyNjc4NTg1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1627989580309-bfaf3e58af6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aXJlbGVzcyUyMGVhcmJ1ZHN8ZW58MXx8fHwxNzYyNjc4NTg1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 42,
    brand: "SoundWave",
    description: "Tai nghe không dây hoàn toàn với âm thanh sống động, điều khiển cảm ứng và tổng thời lượng pin 24 giờ với hộp sạc.",
    specifications: {
      "Thời lượng pin": "6h + 18h (hộp sạc)",
      "Sạc": "USB-C, Không dây",
      "Kháng nước": "IPX7",
      "Driver": "11mm dynamic"
    },
    colors: ["Trắng", "Đen", "Xanh dương"],
    sizes: [],
    featured: false,
    trending: true,
    discount: 22,
  },
  {
    id: 4,
    name: "Laptop cao cấp 15\"",
    category: "Điện tử",
    price: 1299.99,
    originalPrice: 1599.99,
    rating: 4.9,
    reviews: 543,
    image: "https://images.unsplash.com/flagged/photo-1576697010739-6373b63f3204?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYXB0b3AlMjBjb21wdXRlciUyMGRlc2t8ZW58MXx8fHwxNzYyNjY0NTc3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/flagged/photo-1576697010739-6373b63f3204?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYXB0b3AlMjBjb21wdXRlciUyMGRlc2t8ZW58MXx8fHwxNzYyNjY0NTc3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 8,
    brand: "TechBook",
    description: "Hiệu năng mạnh mẽ với Intel i7, 16GB RAM, 512GB SSD. Hoàn hảo cho chuyên gia và nhà sáng tạo.",
    specifications: {
      "Vi xử lý": "Intel Core i7",
      "RAM": "16GB DDR4",
      "Bộ nhớ": "512GB SSD",
      "Màn hình": "15.6\" Full HD"
    },
    colors: ["Xám vũ trụ", "Bạc"],
    sizes: [],
    featured: true,
    trending: false,
    discount: 19,
  },
  {
    id: 5,
    name: "Giày thể thao thiết kế",
    category: "Thời trang",
    price: 189.99,
    originalPrice: 249.99,
    rating: 4.5,
    reviews: 678,
    image: "https://images.unsplash.com/photo-1650320079970-b4ee8f0dae33?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwc25lYWtlcnMlMjBzaG9lc3xlbnwxfHx8fDE3NjI3NjE0ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1650320079970-b4ee8f0dae33?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwc25lYWtlcnMlMjBzaG9lc3xlbnwxfHx8fDE3NjI3NjE0ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 35,
    brand: "StreetStyle",
    description: "Sự thoải mái cao cấp kết hợp phong cách hiện đại. Được chế tác từ vật liệu bền vững và công nghệ đế êm.",
    specifications: {
      "Chất liệu": "Da cao cấp & lưới",
      "Đế giày": "Foam đệm êm",
      "Trọng lượng": "280g/đôi",
      "Bảo quản": "Lau sạch"
    },
    colors: ["Trắng", "Đen", "Đỏ"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    featured: false,
    trending: true,
    discount: 24,
  },
  {
    id: 6,
    name: "Đồng hồ Chronograph cao cấp",
    category: "Thời trang",
    price: 899.99,
    originalPrice: 1199.99,
    rating: 4.9,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1670177257750-9b47927f68eb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjB3YXRjaHxlbnwxfHx8fDE3NjI3MzI1MTN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1670177257750-9b47927f68eb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjB3YXRjaHxlbnwxfHx8fDE3NjI3MzI1MTN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 12,
    brand: "TimeElite",
    description: "Độ chính xác Thụy Sĩ với kính sapphire và vỏ thép không gỉ. Phụ kiện vượt thời gian cho mọi dịp.",
    specifications: {
      "Bộ máy": "Tự động Thụy Sĩ",
      "Vỏ đồng hồ": "44mm Thép không gỉ",
      "Kháng nước": "100m",
      "Kính": "Sapphire"
    },
    colors: ["Bạc", "Vàng", "Đen"],
    sizes: [],
    featured: true,
    trending: false,
    discount: 25,
  },
  {
    id: 7,
    name: "Kính mát cao cấp",
    category: "Thời trang",
    price: 159.99,
    originalPrice: 199.99,
    rating: 4.6,
    reviews: 445,
    image: "https://images.unsplash.com/photo-1756725520224-8fe4bdd87983?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBzdW5nbGFzc2VzfGVufDF8fHx8MTc2Mjc2MTQ4N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1756725520224-8fe4bdd87983?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBzdW5nbGFzc2VzfGVufDF8fHx8MTc2Mjc2MTQ4N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 28,
    brand: "VisionLux",
    description: "Bảo vệ UV400 với tròng kính phân cực. Khung titanium nhẹ cho sự thoải mái cả ngày.",
    specifications: {
      "Tròng kính": "Phân cực UV400",
      "Gọng kính": "Titan",
      "Chiều rộng": "145mm",
      "Chống tia UV": "100% UV"
    },
    colors: ["Đen", "Vân đồi mồi", "Xanh dương"],
    sizes: [],
    featured: false,
    trending: true,
    discount: 20,
  },
  {
    id: 8,
    name: "Túi xách da thiết kế",
    category: "Thời trang",
    price: 349.99,
    originalPrice: 499.99,
    rating: 4.8,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1601924928357-22d3b3abfcfb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZXNpZ25lciUyMGhhbmRiYWd8ZW58MXx8fHwxNzYyNjQ1NjY1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1601924928357-22d3b3abfcfb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZXNpZ25lciUyMGhhbmRiYWd8ZW58MXx8fHwxNzYyNjQ1NjY1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 18,
    brand: "LuxeLeather",
    description: "Túi xách da thật thủ công với nhiều ngăn. Sự kết hợp hoàn hảo giữa phong cách và tiện dụng.",
    specifications: {
      "Chất liệu": "100% Da thật",
      "Kích thước": "35x25x12cm",
      "Ngăn chứa": "3 ngăn chính + 2 ngăn phụ",
      "Khóa": "Nam châm"
    },
    colors: ["Đen", "Nâu", "Đỏ đô"],
    sizes: [],
    featured: false,
    trending: false,
    discount: 30,
  },
  {
    id: 9,
    name: "Bộ cây cảnh trong nhà hiện đại",
    category: "Nhà cửa",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 890,
    image: "https://images.unsplash.com/photo-1613384944189-36c9977e607a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob21lJTIwZGVjb3IlMjBwbGFudHxlbnwxfHx8fDE3NjI3NjE0ODh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1613384944189-36c9977e607a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob21lJTIwZGVjb3IlMjBwbGFudHxlbnwxfHx8fDE3NjI3NjE0ODh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 45,
    brand: "GreenSpace",
    description: "Bộ 3 cây dễ chăm sóc với chậu gốm hiện đại. Hoàn hảo cho mọi không gian sống.",
    specifications: {
      "Bao gồm": "3 cây + chậu",
      "Chất liệu chậu": "Gốm sứ",
      "Độ khó chăm sóc": "Dễ",
      "Ánh sáng": "Thấp đến vừa"
    },
    colors: ["Chậu trắng", "Chậu xám", "Đỏ đất"],
    sizes: ["Nhỏ", "Vừa", "Lớn"],
    featured: false,
    trending: true,
    discount: 20,
  },
  {
    id: 10,
    name: "Ghế thư giãn thiết kế",
    category: "Nhà cửa",
    price: 599.99,
    originalPrice: 799.99,
    rating: 4.8,
    reviews: 321,
    image: "https://images.unsplash.com/photo-1760716478137-d861d5b354e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBmdXJuaXR1cmUlMjBjaGFpcnxlbnwxfHx8fDE3NjI3MjQ3MjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1760716478137-d861d5b354e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBmdXJuaXR1cmUlMjBjaGFpcnxlbnwxfHx8fDE3NjI3MjQ3MjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 6,
    brand: "ModernLiving",
    description: "Thiết kế công thái học với bọc nệm cao cấp. Khung gỗ nguyên khối đảm bảo độ bền và phong cách vượt thời gian.",
    specifications: {
      "Chất liệu": "Gỗ sồi + Nhung",
      "Kích thước": "85x75x90cm",
      "Tải trọng": "150kg",
      "Lắp ráp": "Cần lắp ráp"
    },
    colors: ["Xanh navy", "Xám", "Be"],
    sizes: [],
    featured: true,
    trending: false,
    discount: 25,
  },
  {
    id: 11,
    name: "Bộ máy ảnh chuyên nghiệp",
    category: "Điện tử",
    price: 2499.99,
    originalPrice: 2999.99,
    rating: 4.9,
    reviews: 189,
    image: "https://images.unsplash.com/photo-1579535984712-92fffbbaa266?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYW1lcmElMjBwaG90b2dyYXBoeXxlbnwxfHx8fDE3NjI3MDYyNjF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1579535984712-92fffbbaa266?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYW1lcmElMjBwaG90b2dyYXBoeXxlbnwxfHx8fDE3NjI3MDYyNjF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 4,
    brand: "PhotoPro",
    description: "Máy ảnh mirrorless full-frame với ống kính 24-70mm. Cảm biến 45MP và khả năng quay video 4K.",
    specifications: {
      "Cảm biến": "45MP Full Frame",
      "Video": "4K 60fps",
      "Dải ISO": "100-51200",
      "Bao gồm": "Body + ống kính 24-70mm"
    },
    colors: ["Đen"],
    sizes: [],
    featured: true,
    trending: true,
    discount: 17,
  },
  {
    id: 12,
    name: "Tay cầm chơi game Pro",
    category: "Điện tử",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 1567,
    image: "https://images.unsplash.com/photo-1695028644151-1ec92bae9fb0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnYW1pbmclMjBjb25zb2xlJTIwY29udHJvbGxlcnxlbnwxfHx8fDE3NjI3NjE0ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1695028644151-1ec92bae9fb0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnYW1pbmclMjBjb25zb2xlJTIwY29udHJvbGxlcnxlbnwxfHx8fDE3NjI3NjE0ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 67,
    brand: "GameMaster",
    description: "Tay cầm chơi game không dây với nút tùy chỉnh, đèn RGB và pin 40 giờ.",
    specifications: {
      "Kết nối": "Không dây 2.4GHz + Bluetooth",
      "Pin": "40 giờ",
      "Tính năng": "RGB, Nút tùy chỉnh",
      "Tương thích": "PC, Console, Di động"
    },
    colors: ["Đen", "Trắng", "Đỏ"],
    sizes: [],
    featured: false,
    trending: true,
    discount: 20,
  },
];

export const categories = [
  { name: "Điện tử", icon: "Laptop", count: 1245 },
  { name: "Thời trang", icon: "Shirt", count: 3421 },
  { name: "Nhà cửa", icon: "Home", count: 892 },
  { name: "Thể thao", icon: "Dumbbell", count: 567 },
  { name: "Làm đẹp", icon: "Sparkles", count: 1123 },
  { name: "Sách", icon: "BookOpen", count: 2341 },
];

export const reviews = [
  {
    id: 1,
    productId: 1,
    user: "Sarah Johnson",
    avatar: "SJ",
    rating: 5,
    date: "2025-11-05",
    comment: "Tôi rất yêu thích tai nghe này! Chống ồn tuyệt vời và chất lượng âm thanh hàng đầu.",
    helpful: 24,
  },
  {
    id: 2,
    productId: 1,
    user: "Mike Chen",
    avatar: "MC",
    rating: 4,
    date: "2025-11-02",
    comment: "Sản phẩm tốt nhìn chung. Pin đúng như quảng cáo. Vấn đề nhỏ duy nhất là trọng lượng sau khi dùng lâu.",
    helpful: 12,
  },
  {
    id: 3,
    productId: 1,
    user: "Emma Davis",
    avatar: "ED",
    rating: 5,
    date: "2025-10-28",
    comment: "Mua sắm tốt nhất năm nay. Hoàn hảo cho di chuyển hàng ngày và làm việc tại nhà.",
    helpful: 18,
  },
];

export const orders = [
  {
    id: "ORD-2025-001234",
    date: "2025-11-08",
    status: "Đã giao hàng",
    total: 749.97,
    items: [
      { productId: 1, quantity: 1, price: 299.99 },
      { productId: 3, quantity: 2, price: 179.99 },
    ],
    tracking: {
      current: "delivered",
      steps: [
        { status: "ordered", label: "Đã đặt hàng", date: "Nov 8, 10:30 AM", completed: true },
        { status: "confirmed", label: "Đã xác nhận", date: "Nov 8, 10:35 AM", completed: true },
        { status: "shipped", label: "Đã giao cho vận chuyển", date: "Nov 8, 2:15 PM", completed: true },
        { status: "out_for_delivery", label: "Đang giao hàng", date: "Nov 9, 8:00 AM", completed: true },
        { status: "delivered", label: "Đã giao hàng", date: "Nov 9, 4:30 PM", completed: true },
      ],
    },
  },
  {
    id: "ORD-2025-001189",
    date: "2025-11-05",
    status: "Đang giao hàng",
    total: 449.99,
    items: [
      { productId: 2, quantity: 1, price: 449.99 },
    ],
    tracking: {
      current: "out_for_delivery",
      steps: [
        { status: "ordered", label: "Đã đặt hàng", date: "Nov 5, 2:20 PM", completed: true },
        { status: "confirmed", label: "Đã xác nhận", date: "Nov 5, 2:25 PM", completed: true },
        { status: "shipped", label: "Đã giao cho vận chuyển", date: "Nov 6, 9:00 AM", completed: true },
        { status: "out_for_delivery", label: "Đang giao hàng", date: "Nov 10, 7:00 AM", completed: true },
        { status: "delivered", label: "Đã giao hàng", date: "Dự kiến hôm nay", completed: false },
      ],
    },
  },
  {
    id: "ORD-2025-001098",
    date: "2025-10-28",
    status: "Đã giao hàng",
    total: 1299.99,
    items: [
      { productId: 4, quantity: 1, price: 1299.99 },
    ],
    tracking: {
      current: "delivered",
      steps: [
        { status: "ordered", label: "Đã đặt hàng", date: "Oct 28, 11:15 AM", completed: true },
        { status: "confirmed", label: "Đã xác nhận", date: "Oct 28, 11:20 AM", completed: true },
        { status: "shipped", label: "Đã giao cho vận chuyển", date: "Oct 29, 10:00 AM", completed: true },
        { status: "out_for_delivery", label: "Đang giao hàng", date: "Oct 31, 8:30 AM", completed: true },
        { status: "delivered", label: "Đã giao hàng", date: "Oct 31, 3:45 PM", completed: true },
      ],
    },
  },
];

export const messages = [
  {
    id: 1,
    sellerId: "seller-001",
    sellerName: "AudioPro Official",
    sellerAvatar: "AP",
    lastMessage: "Sản phẩm sẽ được gửi vào sáng mai!",
    timestamp: "2 giờ trước",
    unread: 2,
    messages: [
      { sender: "buyer", text: "Xin chào, khi nào đơn hàng của tôi được gửi?", timestamp: "10:30 AM" },
      { sender: "seller", text: "Chào bạn! Để tôi kiểm tra giúp bạn.", timestamp: "10:32 AM" },
      { sender: "seller", text: "Sản phẩm sẽ được gửi vào sáng mai!", timestamp: "10:35 AM" },
      { sender: "buyer", text: "Tuyệt vời, cảm ơn bạn!", timestamp: "10:36 AM" },
    ],
  },
  {
    id: 2,
    sellerId: "seller-002",
    sellerName: "TechWatch Store",
    sellerAvatar: "TW",
    lastMessage: "Có, chúng tôi còn màu đó!",
    timestamp: "1 ngày trước",
    unread: 0,
    messages: [
      { sender: "buyer", text: "Bạn có mẫu màu vàng hồng không?", timestamp: "Yesterday 3:20 PM" },
      { sender: "seller", text: "Có, chúng tôi còn màu đó!", timestamp: "Yesterday 3:25 PM" },
    ],
  },
];

export const dashboardStats = {
  totalRevenue: 125430,
  totalOrders: 1834,
  totalProducts: 156,
  totalCustomers: 8934,
  revenueChange: 12.5,
  ordersChange: 8.2,
  productsChange: 3.1,
  customersChange: 15.7,
};

export const salesData = [
  { month: "Jan", revenue: 12400, orders: 234 },
  { month: "Feb", revenue: 15600, orders: 289 },
  { month: "Mar", revenue: 13200, orders: 256 },
  { month: "Apr", revenue: 18900, orders: 342 },
  { month: "May", revenue: 21200, orders: 398 },
  { month: "Jun", revenue: 19800, orders: 367 },
  { month: "Jul", revenue: 23400, orders: 421 },
  { month: "Aug", revenue: 26700, orders: 489 },
  { month: "Sep", revenue: 24500, orders: 456 },
  { month: "Oct", revenue: 28900, orders: 512 },
  { month: "Nov", revenue: 31200, orders: 578 },
];
