export const products = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    category: "Electronics",
    price: 299.99,
    originalPrice: 399.99,
    rating: 4.8,
    reviews: 1243,
    image: "https://images.unsplash.com/photo-1761005653657-0885604ddbcd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcmVtaXVtJTIwaGVhZHBob25lcyUyMGVsZWN0cm9uaWNzfGVufDF8fHx8MTc2Mjc2MTQ4NXww&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1761005653657-0885604ddbcd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcmVtaXVtJTIwaGVhZHBob25lcyUyMGVsZWN0cm9uaWNzfGVufDF8fHx8MTc2Mjc2MTQ4NXww&ixlib=rb-4.1.0&q=80&w=1080",
      "https://images.unsplash.com/photo-1761005653657-0885604ddbcd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcmVtaXVtJTIwaGVhZHBob25lcyUyMGVsZWN0cm9uaWNzfGVufDF8fHx8MTc2Mjc2MTQ4NXww&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 24,
    brand: "AudioPro",
    description: "Experience premium sound quality with active noise cancellation and 40-hour battery life. Perfect for music lovers and professionals.",
    specifications: {
      "Battery Life": "40 hours",
      "Connectivity": "Bluetooth 5.2",
      "Weight": "250g",
      "Driver Size": "40mm"
    },
    colors: ["Black", "Silver", "Navy"],
    sizes: [],
    featured: true,
    trending: true,
    discount: 25,
  },
  {
    id: 2,
    name: "Smart Watch Pro",
    category: "Electronics",
    price: 449.99,
    originalPrice: 549.99,
    rating: 4.6,
    reviews: 892,
    image: "https://images.unsplash.com/photo-1758348844371-dfbae2780bd3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBzbWFydHdhdGNoJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NjI3MDQ2MzB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1758348844371-dfbae2780bd3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBzbWFydHdhdGNoJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NjI3MDQ2MzB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 15,
    brand: "TechWatch",
    description: "Stay connected with advanced health monitoring, GPS, and customizable watch faces. Water-resistant up to 50m.",
    specifications: {
      "Display": "1.9 AMOLED",
      "Battery": "3 days",
      "Water Resistance": "50m",
      "Sensors": "Heart rate, SpO2, GPS"
    },
    colors: ["Black", "Rose Gold", "Titanium"],
    sizes: ["42mm", "46mm"],
    featured: true,
    trending: false,
    discount: 18,
  },
  {
    id: 3,
    name: "Wireless Earbuds Elite",
    category: "Electronics",
    price: 179.99,
    originalPrice: 229.99,
    rating: 4.7,
    reviews: 2156,
    image: "https://images.unsplash.com/photo-1627989580309-bfaf3e58af6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aXJlbGVzcyUyMGVhcmJ1ZHN8ZW58MXx8fHwxNzYyNjc4NTg1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1627989580309-bfaf3e58af6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aXJlbGVzcyUyMGVhcmJ1ZHN8ZW58MXx8fHwxNzYyNjc4NTg1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 42,
    brand: "SoundWave",
    description: "True wireless earbuds with immersive sound, touch controls, and 24-hour total battery life with charging case.",
    specifications: {
      "Battery Life": "6h + 18h case",
      "Charging": "USB-C, Wireless",
      "Water Rating": "IPX7",
      "Driver": "11mm dynamic"
    },
    colors: ["White", "Black", "Blue"],
    sizes: [],
    featured: false,
    trending: true,
    discount: 22,
  },
  {
    id: 4,
    name: "Premium Laptop 15\"",
    category: "Electronics",
    price: 1299.99,
    originalPrice: 1599.99,
    rating: 4.9,
    reviews: 543,
    image: "https://images.unsplash.com/flagged/photo-1576697010739-6373b63f3204?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYXB0b3AlMjBjb21wdXRlciUyMGRlc2t8ZW58MXx8fHwxNzYyNjY0NTc3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/flagged/photo-1576697010739-6373b63f3204?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYXB0b3AlMjBjb21wdXRlciUyMGRlc2t8ZW58MXx8fHwxNzYyNjY0NTc3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 8,
    brand: "TechBook",
    description: "Powerful performance with Intel i7, 16GB RAM, 512GB SSD. Perfect for professionals and creators.",
    specifications: {
      "Processor": "Intel Core i7",
      "RAM": "16GB DDR4",
      "Storage": "512GB SSD",
      "Display": "15.6\" Full HD"
    },
    colors: ["Space Gray", "Silver"],
    sizes: [],
    featured: true,
    trending: false,
    discount: 19,
  },
  {
    id: 5,
    name: "Designer Sneakers",
    category: "Fashion",
    price: 189.99,
    originalPrice: 249.99,
    rating: 4.5,
    reviews: 678,
    image: "https://images.unsplash.com/photo-1650320079970-b4ee8f0dae33?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwc25lYWtlcnMlMjBzaG9lc3xlbnwxfHx8fDE3NjI3NjE0ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1650320079970-b4ee8f0dae33?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwc25lYWtlcnMlMjBzaG9lc3xlbnwxfHx8fDE3NjI3NjE0ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 35,
    brand: "StreetStyle",
    description: "Premium comfort meets modern style. Crafted with sustainable materials and cushioned sole technology.",
    specifications: {
      "Material": "Premium leather & mesh",
      "Sole": "Cushion foam",
      "Weight": "280g per shoe",
      "Care": "Wipe clean"
    },
    colors: ["White", "Black", "Red"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    featured: false,
    trending: true,
    discount: 24,
  },
  {
    id: 6,
    name: "Luxury Chronograph Watch",
    category: "Fashion",
    price: 899.99,
    originalPrice: 1199.99,
    rating: 4.9,
    reviews: 234,
    image: "https://images.unsplash.com/photo-1670177257750-9b47927f68eb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjB3YXRjaHxlbnwxfHx8fDE3NjI3MzI1MTN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1670177257750-9b47927f68eb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjB3YXRjaHxlbnwxfHx8fDE3NjI3MzI1MTN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 12,
    brand: "TimeElite",
    description: "Swiss-made precision with sapphire crystal and stainless steel case. A timeless accessory for any occasion.",
    specifications: {
      "Movement": "Swiss Automatic",
      "Case": "44mm Stainless Steel",
      "Water Resistance": "100m",
      "Crystal": "Sapphire"
    },
    colors: ["Silver", "Gold", "Black"],
    sizes: [],
    featured: true,
    trending: false,
    discount: 25,
  },
  {
    id: 7,
    name: "Premium Sunglasses",
    category: "Fashion",
    price: 159.99,
    originalPrice: 199.99,
    rating: 4.6,
    reviews: 445,
    image: "https://images.unsplash.com/photo-1756725520224-8fe4bdd87983?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBzdW5nbGFzc2VzfGVufDF8fHx8MTc2Mjc2MTQ4N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1756725520224-8fe4bdd87983?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBzdW5nbGFzc2VzfGVufDF8fHx8MTc2Mjc2MTQ4N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 28,
    brand: "VisionLux",
    description: "UV400 protection with polarized lenses. Lightweight titanium frame for all-day comfort.",
    specifications: {
      "Lens": "Polarized UV400",
      "Frame": "Titanium",
      "Width": "145mm",
      "Protection": "100% UV"
    },
    colors: ["Black", "Tortoise", "Blue"],
    sizes: [],
    featured: false,
    trending: true,
    discount: 20,
  },
  {
    id: 8,
    name: "Designer Leather Handbag",
    category: "Fashion",
    price: 349.99,
    originalPrice: 499.99,
    rating: 4.8,
    reviews: 567,
    image: "https://images.unsplash.com/photo-1601924928357-22d3b3abfcfb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZXNpZ25lciUyMGhhbmRiYWd8ZW58MXx8fHwxNzYyNjQ1NjY1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1601924928357-22d3b3abfcfb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZXNpZ25lciUyMGhhbmRiYWd8ZW58MXx8fHwxNzYyNjQ1NjY1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 18,
    brand: "LuxeLeather",
    description: "Handcrafted genuine leather handbag with multiple compartments. Perfect blend of style and functionality.",
    specifications: {
      "Material": "100% Genuine Leather",
      "Dimensions": "35x25x12cm",
      "Compartments": "3 main + 2 side",
      "Closure": "Magnetic snap"
    },
    colors: ["Black", "Brown", "Burgundy"],
    sizes: [],
    featured: false,
    trending: false,
    discount: 30,
  },
  {
    id: 9,
    name: "Modern Indoor Plant Set",
    category: "Home",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 890,
    image: "https://images.unsplash.com/photo-1613384944189-36c9977e607a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob21lJTIwZGVjb3IlMjBwbGFudHxlbnwxfHx8fDE3NjI3NjE0ODh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1613384944189-36c9977e607a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob21lJTIwZGVjb3IlMjBwbGFudHxlbnwxfHx8fDE3NjI3NjE0ODh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 45,
    brand: "GreenSpace",
    description: "Set of 3 low-maintenance plants with modern ceramic pots. Perfect for any living space.",
    specifications: {
      "Includes": "3 plants + pots",
      "Pot Material": "Ceramic",
      "Care Level": "Easy",
      "Light": "Low to medium"
    },
    colors: ["White Pots", "Gray Pots", "Terracotta"],
    sizes: ["Small", "Medium", "Large"],
    featured: false,
    trending: true,
    discount: 20,
  },
  {
    id: 10,
    name: "Designer Lounge Chair",
    category: "Home",
    price: 599.99,
    originalPrice: 799.99,
    rating: 4.8,
    reviews: 321,
    image: "https://images.unsplash.com/photo-1760716478137-d861d5b354e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBmdXJuaXR1cmUlMjBjaGFpcnxlbnwxfHx8fDE3NjI3MjQ3MjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1760716478137-d861d5b354e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBmdXJuaXR1cmUlMjBjaGFpcnxlbnwxfHx8fDE3NjI3MjQ3MjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 6,
    brand: "ModernLiving",
    description: "Ergonomic design with premium upholstery. Solid wood frame ensures durability and timeless style.",
    specifications: {
      "Material": "Oak wood + Velvet",
      "Dimensions": "85x75x90cm",
      "Weight Capacity": "150kg",
      "Assembly": "Required"
    },
    colors: ["Navy", "Gray", "Beige"],
    sizes: [],
    featured: true,
    trending: false,
    discount: 25,
  },
  {
    id: 11,
    name: "Professional Camera Kit",
    category: "Electronics",
    price: 2499.99,
    originalPrice: 2999.99,
    rating: 4.9,
    reviews: 189,
    image: "https://images.unsplash.com/photo-1579535984712-92fffbbaa266?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYW1lcmElMjBwaG90b2dyYXBoeXxlbnwxfHx8fDE3NjI3MDYyNjF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1579535984712-92fffbbaa266?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYW1lcmElMjBwaG90b2dyYXBoeXxlbnwxfHx8fDE3NjI3MDYyNjF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 4,
    brand: "PhotoPro",
    description: "Full-frame mirrorless camera with 24-70mm lens. 45MP sensor and 4K video recording capabilities.",
    specifications: {
      "Sensor": "45MP Full Frame",
      "Video": "4K 60fps",
      "ISO Range": "100-51200",
      "Includes": "Body + 24-70mm lens"
    },
    colors: ["Black"],
    sizes: [],
    featured: true,
    trending: true,
    discount: 17,
  },
  {
    id: 12,
    name: "Gaming Controller Pro",
    category: "Electronics",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 1567,
    image: "https://images.unsplash.com/photo-1695028644151-1ec92bae9fb0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnYW1pbmclMjBjb25zb2xlJTIwY29udHJvbGxlcnxlbnwxfHx8fDE3NjI3NjE0ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1695028644151-1ec92bae9fb0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnYW1pbmclMjBjb25zb2xlJTIwY29udHJvbGxlcnxlbnwxfHx8fDE3NjI3NjE0ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    ],
    stock: 67,
    brand: "GameMaster",
    description: "Wireless gaming controller with customizable buttons, RGB lighting, and 40-hour battery life.",
    specifications: {
      "Connectivity": "Wireless 2.4GHz + Bluetooth",
      "Battery": "40 hours",
      "Features": "RGB, Programmable buttons",
      "Compatible": "PC, Console, Mobile"
    },
    colors: ["Black", "White", "Red"],
    sizes: [],
    featured: false,
    trending: true,
    discount: 20,
  },
];

export const categories = [
  { name: "Electronics", icon: "Laptop", count: 1245 },
  { name: "Fashion", icon: "Shirt", count: 3421 },
  { name: "Home", icon: "Home", count: 892 },
  { name: "Sports", icon: "Dumbbell", count: 567 },
  { name: "Beauty", icon: "Sparkles", count: 1123 },
  { name: "Books", icon: "BookOpen", count: 2341 },
];

export const reviews = [
  {
    id: 1,
    productId: 1,
    user: "Sarah Johnson",
    avatar: "SJ",
    rating: 5,
    date: "2025-11-05",
    comment: "Absolutely love these headphones! The noise cancellation is incredible and the sound quality is top-notch.",
    helpful: 24,
  },
  {
    id: 2,
    productId: 1,
    user: "Mike Chen",
    avatar: "MC",
    rating: 4,
    date: "2025-11-02",
    comment: "Great product overall. Battery life is as advertised. Only minor issue is the weight after long sessions.",
    helpful: 12,
  },
  {
    id: 3,
    productId: 1,
    user: "Emma Davis",
    avatar: "ED",
    rating: 5,
    date: "2025-10-28",
    comment: "Best purchase I've made this year. Perfect for my daily commute and work from home setup.",
    helpful: 18,
  },
];

export const orders = [
  {
    id: "ORD-2025-001234",
    date: "2025-11-08",
    status: "Delivered",
    total: 749.97,
    items: [
      { productId: 1, quantity: 1, price: 299.99 },
      { productId: 3, quantity: 2, price: 179.99 },
    ],
    tracking: {
      current: "delivered",
      steps: [
        { status: "ordered", label: "Order Placed", date: "Nov 8, 10:30 AM", completed: true },
        { status: "confirmed", label: "Order Confirmed", date: "Nov 8, 10:35 AM", completed: true },
        { status: "shipped", label: "Shipped", date: "Nov 8, 2:15 PM", completed: true },
        { status: "out_for_delivery", label: "Out for Delivery", date: "Nov 9, 8:00 AM", completed: true },
        { status: "delivered", label: "Delivered", date: "Nov 9, 4:30 PM", completed: true },
      ],
    },
  },
  {
    id: "ORD-2025-001189",
    date: "2025-11-05",
    status: "Out for Delivery",
    total: 449.99,
    items: [
      { productId: 2, quantity: 1, price: 449.99 },
    ],
    tracking: {
      current: "out_for_delivery",
      steps: [
        { status: "ordered", label: "Order Placed", date: "Nov 5, 2:20 PM", completed: true },
        { status: "confirmed", label: "Order Confirmed", date: "Nov 5, 2:25 PM", completed: true },
        { status: "shipped", label: "Shipped", date: "Nov 6, 9:00 AM", completed: true },
        { status: "out_for_delivery", label: "Out for Delivery", date: "Nov 10, 7:00 AM", completed: true },
        { status: "delivered", label: "Delivered", date: "Expected today", completed: false },
      ],
    },
  },
  {
    id: "ORD-2025-001098",
    date: "2025-10-28",
    status: "Delivered",
    total: 1299.99,
    items: [
      { productId: 4, quantity: 1, price: 1299.99 },
    ],
    tracking: {
      current: "delivered",
      steps: [
        { status: "ordered", label: "Order Placed", date: "Oct 28, 11:15 AM", completed: true },
        { status: "confirmed", label: "Order Confirmed", date: "Oct 28, 11:20 AM", completed: true },
        { status: "shipped", label: "Shipped", date: "Oct 29, 10:00 AM", completed: true },
        { status: "out_for_delivery", label: "Out for Delivery", date: "Oct 31, 8:30 AM", completed: true },
        { status: "delivered", label: "Delivered", date: "Oct 31, 3:45 PM", completed: true },
      ],
    },
  },
];

export const messages = [
  {
    id: 1,
    sellerId: "seller-001",
    sellerName: "AudioPro Official",
    sellerAvatar: "AP",
    lastMessage: "The product will be shipped tomorrow morning!",
    timestamp: "2 hours ago",
    unread: 2,
    messages: [
      { sender: "buyer", text: "Hello, when will my order ship?", timestamp: "10:30 AM" },
      { sender: "seller", text: "Hi! Let me check that for you.", timestamp: "10:32 AM" },
      { sender: "seller", text: "The product will be shipped tomorrow morning!", timestamp: "10:35 AM" },
      { sender: "buyer", text: "Great, thank you!", timestamp: "10:36 AM" },
    ],
  },
  {
    id: 2,
    sellerId: "seller-002",
    sellerName: "TechWatch Store",
    sellerAvatar: "TW",
    lastMessage: "Yes, we have that color in stock!",
    timestamp: "1 day ago",
    unread: 0,
    messages: [
      { sender: "buyer", text: "Do you have the rose gold variant?", timestamp: "Yesterday 3:20 PM" },
      { sender: "seller", text: "Yes, we have that color in stock!", timestamp: "Yesterday 3:25 PM" },
    ],
  },
];

export const dashboardStats = {
  totalRevenue: 125430,
  totalOrders: 1834,
  totalProducts: 156,
  totalCustomers: 8934,
  revenueChange: 12.5,
  ordersChange: 8.2,
  productsChange: 3.1,
  customersChange: 15.7,
};

export const salesData = [
  { month: "Jan", revenue: 12400, orders: 234 },
  { month: "Feb", revenue: 15600, orders: 289 },
  { month: "Mar", revenue: 13200, orders: 256 },
  { month: "Apr", revenue: 18900, orders: 342 },
  { month: "May", revenue: 21200, orders: 398 },
  { month: "Jun", revenue: 19800, orders: 367 },
  { month: "Jul", revenue: 23400, orders: 421 },
  { month: "Aug", revenue: 26700, orders: 489 },
  { month: "Sep", revenue: 24500, orders: 456 },
  { month: "Oct", revenue: 28900, orders: 512 },
  { month: "Nov", revenue: 31200, orders: 578 },
];
